# Generated by Django 5.0.6 on 2024-06-18 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Imya')),
            ],
            options={
                'verbose_name': 'Pobeda',
                'verbose_name_plural': 'Pobedi',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='bb',
            options={'ordering': ['-publish'], 'verbose_name': 'Yra', 'verbose_name_plural': 'Yrara'},
        ),
        migrations.AlterField(
            model_name='bb',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='kontent'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='name',
            field=models.CharField(max_length=50, verbose_name='nazvanie'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='cena'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='publish',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='pupliш'),
        ),
        migrations.AddField(
            model_name='bb',
            name='rubric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bboard.rubric', verbose_name='Rubrica'),
        ),
    ]
